# Generated by Django 4.2.26 on 2025-11-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('fullName', models.CharField(max_length=255)),
                ('functionSummary', models.TextField()),
            ],
        ),
    ]
