# Generated by Django 4.2.26 on 2025-11-25 02:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVariantReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patientId', models.UUIDField()),
                ('detectionDate', models.DateField()),
                ('alleleFrequency', models.DecimalField(decimal_places=3, max_digits=5)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_reports', to='variants.geneticvariant')),
            ],
        ),
    ]
