# Generated by Django 4.2.26 on 2025-11-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvariantreport',
            name='patientId',
            field=models.CharField(max_length=255),
        ),
    ]
