# Generated by Django 4.2.26 on 2025-11-25 02:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneticVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chromosome', models.CharField(max_length=10)),
                ('position', models.IntegerField()),
                ('referenceBase', models.CharField(max_length=5)),
                ('alternateBase', models.CharField(max_length=5)),
                ('impact', models.CharField(max_length=50)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='genes.gene')),
            ],
        ),
    ]
